DROP TABLE IF EXISTS links;

CREATE TABLE IF NOT EXISTS links (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `url` TEXT NOT NULL,
  `slug` VARCHAR(50) NOT NULL UNIQUE,
  `cinfo` TEXT,
  `ctime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_links_slug ON links(`slug`);