DROP TABLE IF EXISTS links;

CREATE TABLE IF NOT EXISTS links (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `url` TEXT NOT NULL,
  `slug` VARCHAR(50) NOT NULL UNIQUE,
  `cinfo` TEXT,
  `ctime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_links_slug ON links(`slug`);

DROP TABLE IF EXISTS logs;

CREATE TABLE IF NOT EXISTS logs (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `slug` VARCHAR(50) NOT NULL,
  `cinfo` TEXT,
  `ctime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`slug`) REFERENCES links(`slug`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_logs_slug ON logs(`slug`);